import React, { Component } from 'react';

import './_terms.css';


class Terms extends Component {

    render() {
        return (
            <section className="privacy-section">
                <div className="container-fluid big-container">
                    <div className="col-12">
                        <p className="privacy-section__txt fs18 c-gray font-medium">Welcome to Agentero!</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">These terms and conditions are a legal agreement (the “Terms”) between you (“You”) and Agentero, Inc., with offices at 1714 Franklin st #100-298, Oakland, CA 94612, USA (“Agentero” or “we”, “us” or “our”), establishing terms and conditions under which You shall access and use the services and features available on Agentero’s web-based and/or mobile application platform (the “Agentero Platform”). The Agentero Platform enables insurance policyholders and consumers of insurance products and policies to manage insurance policies and interact with insurance agents (“Agents”).</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">PLEASE READ THESE TERMS CAREFULLY. BY USING THIS PLATFORM OR OBTAINING ANY SERVICES FROM AGENTERO, YOU INDICATE YOUR ACCEPTANCE OF THESE TERMS. IF YOU DO NOT ACCEPT ANY OF THESE TERMS, THEN PLEASE DO NOT USE THIS PLATFORM. YOU SHOULD PRINT OR OTHERWISE SAVE A COPY OF THESE TERMS FOR YOUR RECORDS.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">FURTHER, THESE TERMS CONTAIN AN AGREEMENT TO ARBITRATE, WHICH REQUIRES THAT YOU AND AGENTERO ARBITRATE CERTAIN CLAIMS BY BINDING, INDIVIDUAL ARBITRATION INSTEAD OF GOING TO COURT AND LIMITS CLASS ACTION CLAIMS UNLESS YOU OPT OUT AS PROVIDED IN SUCH AGREEMENT TO ARBITRATE (SEE SECTION 6 “AGREEMENT TO ARBITRATE”).</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Agentero reserves the right to revise these Terms in its sole discretion at any time and without prior notice to You other than by posting the revised Terms on http://www.agentero.com/ (our “Website”). Revisions to the Terms are effective upon posting. Your continued use of the Agentero Platform after a revised version of these Terms has been posted on our Website constitutes Your binding acceptance of the revised Terms.</p>
                        <h2 className="privacy-section__title fs18 c-gray font-bold">1. AGENTERO PLATFORM.</h2>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Access and Use. Subject to these Terms, Agentero hereby grants to You a limited, non-exclusive, non-transferable right to access and use the Agentero Platform, solely for Your personal or business insurance purposes. You are responsible for maintaining the confidentiality of all user logins and passwords and for ensuring that each user login and password is used only by You. You are solely responsible for any and all access and use of the Agentero Platform that occurs under Your account. You shall not, directly or indirectly, and You shall not permit any third party to, (i)reverse engineer, decompile, disassemble or otherwise attempt to discover the object code, source code or underlying ideas or algorithms of the Agentero Platform; (ii) modify, translate, or create derivative works based on any element of the Agentero Platform or any related documentation; (iii) rent, lease, distribute, sell, resell, assign, or otherwise transfer its rights to use the Agentero Platform; (iv) use the Agentero Platform for timesharing purposes or otherwise for the benefit of any person or entity other than You; (v) use the Agentero Platform for any purpose other than its intended purpose; or (vi) interfere with or disrupt the integrity or performance of the Agentero Platform.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Interactions and Financial Arrangements between Agents and Policyholders. You acknowledge that Agentero is not responsible for any acts or omissions of any Agents that You may interact with through the Agentero Platform. Further, the Agentero Platform may enable You to provide credit card, financial or other information to Agents. You acknowledge that Agentero does not control how any Agent utilizes information they receive from You.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Agentero is not an Agent of Insurance Products or Policies. You agree and acknowledge that Agentero is not an agent, broker or seller of insurance products or policies. You agree and acknowledge that, as between You and Agentero, (i) any insurance products or policies You purchase from an Agent through the Agentero Platform are at Your sole risk and (ii) Agentero is not responsible for the quality or correctness of the information, insurance policies, data or other content uploaded to the Agentero Platform by Agents (“Agent Content”). The purchase and sale of insurance products and policies is between You and the Agent according to any separate terms and conditions as You and the Agent may agree from time to time. It is Your responsibility to evaluate the accuracy, completeness or usefulness of any information, opinion, advice or other content available through the Agentero Platform. You are responsible for seeking the advice of legal, financial or other professionals, as appropriate, regarding the evaluation of any specific information, opinion, advice or other Agent Content.</p>
                        <h2 className="privacy-section__title fs18 c-gray font-bold">2. YOUR CONTENT</h2>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Your Content. You, not Agentero, shall be solely responsible for the accuracy, quality, integrity, legality, reliability, appropriateness of and the parties’ respective rights to use all Your Content (as defined below) under these Terms.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">File Uploads. Agentero may allow You to upload files to the Agentero Platform. You agree that any files uploaded to the Agentero Platform will be insurance policy documents. You will not upload any files that are not insurance policy documents. You agree that You will only upload insurance policy documents for policies under which You are an insured party. You are responsible for obtaining any consents and other rights necessary to upload insurance policy documents to the Agentero Platform under which other individuals are also insured parties.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Personally Identifiable Information. You may be required to disclose certain PII in order to use the Agentero Platform. The information that You disclose through the Platform may include, without limitation, Your name and address, e-mail address, telephone number, geographic location, and such other information as determined by Agentero from time to time (“Your Information”), which will be stored under Your account page (“Account”). Your Information entered into the Agentero Platform may contain PII which may be made available to Agents. You agree and acknowledge that You will provide accurate, complete, and up to date information as requested. You further agree and acknowledges that Your submission of PII to Agentero is voluntary and entirely at Your own risk. You agree and acknowledge that Your Information may be disclosed to an Agent in connection with Your use of the Agentero Platform. As used herein, “PII” means information that can be used to identify, contact, locate, distinguish or trace an individual’s identity, either alone or when combined with other personal or identifying information that is linked or linkable to a specific individual.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Your Content Warranty. You represent and warrant that (a) You have the right, including in respect of all relevant Intellectual Property Rights and applicable data privacy and other laws, to provide Agentero access to and use of Your Content within the scope permitted under this Agreement, including without limitation, for use in connection with the Agentero Platform, and (b) You will ensure that Your submission, collection and use of Your Content in connection with the Agentero Platform complies with all applicable laws, rules and regulations and these Terms.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Mobile App. By using the Agentero downloadable mobile application (“Agentero App”), You agree that all of the terms and conditions found herein apply to Your use of the Agentero App. Additionally, You agree that the Agentero App may send You push notifications if You turn on receipt of notifications and/or sign up to receive notifications. The Agentero App may also send You autodialed SMS/text messages to the telephone number You provide, if You consent to receive such messages. Your carrier’s normal messaging, data and other rates and fees will apply to these communications. You may opt-out of receiving SMS/text messages at any time by replying STOP to any message or, when such functionality is available on the Agentero App, by updating settings in the Agentero App. You further acknowledge that Your use of the Agentero App may require use of Your data plan from Your cellular provider. You are responsible for payment of all data usage accrued based on Your use of the Agentero App, and Agentero disclaims all responsibility for such data usage. In addition, if You allow the Agentero App to utilize location services, the Agentero App may collect Your geographic location to set Your location for use of the Agentero Platform.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Usage Data. Notwithstanding anything else in the Terms or otherwise, Agentero may monitor Your use of the Agentero Platform and use data and information related to Your Content and Your use of the Agentero Platform in an aggregate or de-identified manner, including to compile statistical and performance information related to the provision and operation of the Agentero Platform. You agree that Agentero may make such data and information publicly available, and use such information to the extent and in the manner required by applicable law or regulation and/or for purposes of data gathering, analysis, service enhancement and marketing, provided that such data and information does not identify You. Agentero retains all intellectual property rights or similar proprietary rights, including (a) patent rights and utility models, (b) copyrights and database rights, (c) trademarks, trade names, domain names and trade dress and the goodwill associated therewith, and (d) trade secrets; in each case, including any registrations of, applications to register, and renewals and extensions of, any of the foregoing in any jurisdiction in the world (“Intellectual Property Rights”) in such aggregated or de-identified data and information.</p>
                        <h2 className="privacy-section__title fs18 c-gray font-bold">3. PROPRIETARY RIGHTS.</h2>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Ownership. You acknowledge that the Agentero Platform, and all Intellectual Property Rights therein and all improvements thereto, are the sole and exclusive property of Agentero and its licensors.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">License to Your Content. You grant to Agentero a royalty-free, nonexclusive, irrevocable, limited right and license to use content and information uploaded to and stored in the Agentero Platform by You, in connection with Your use of the Agentero Platform, including Your Information and copies of insurance policy documents (“Your Content”) (a) in order to provide access to the Agentero Platform; (b) to analyze and improve the Agentero Platform; and/or (c) to compile and use aggregate or de-identified data, statistics, measurements or other metrics derived from Your Content (including in combination with the aggregate or de-identified customer data of other Agentero customers) for its own purposes. Aggregate or de-identified data means data that does not identify You or any individual.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Disclosure of Your Content. Agentero shall not disclose Your Content to third parties, except: (i) as necessary to enable You to access and use the Agentero Platform; (ii) to our service providers who are not permitted to use such data except on behalf of Agentero, (iii) as required by law or to comply with legal process; (iv) to protect and defend the rights or property of Agentero, including as evidence in litigation; (v) to troubleshoot problems with the Agentero Platform; (vi) to any successor in interest, including as part of a merger, acquisition or transfer of assets, or as part of a bankruptcy proceeding; or (vii) in aggregate or de-identified form.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Limited Feedback License. You hereby grant to Agentero, at no charge, a non-exclusive, royalty-free, worldwide, transferable, sublicensable (through one or more tiers), perpetual, irrevocable license under Your Intellectual Property Rights in and to suggestions, comments and other forms of feedback (“Feedback”) regarding the Agentero Platform and Agentero Developments provided by You or on Your behalf to Agentero, including Feedback regarding features, usability and use, and bug reports, to reproduce, perform, display, create derivative works of the Feedback and distribute such Feedback and/or derivative works in the Agentero Platform or any other products or services. Feedback is provided “as is” without warranty of any kind.</p>
                        <h2 className="privacy-section__title fs18 c-gray font-bold">4. LIMITATION OF LIABILITY.</h2>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Disclaimer of Warranty. YOU acknowledge that the AGENTERO PLATFORM and ALL SERVICES, TEXT, IMAGES AND OTHER INFORMATION ON OR ACCESSIBLE FROM THE AGENTERO PLATFORM ARE PROVIDED “AS IS” and are based in part on CONTENT provided by AGENTS, which IS not verified by AGENTERO, and that any INSURANCE POLICIES PURCHASED OR acquired through the use of the AGENTERO PLATFORM OR SERVICES is UNDERTAKEN at YOUR sole risk and discretion. AGENTERO and AGENTERO’s affiliates, agents, directors, officers, employees, investors, suppliers and licensors are not liable or responsible for any result generated through the use of the AGENTERO PLATFORM. AGENTERO PROVIDEs NO OTHER WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. SPECIFICALLY, BUT WITHOUT LIMITATION, none of AGENTERO OR AGENTERO’s affiliates, agents, directors, officers, employees, investors, suppliers OR licensors WARRANT THAT: (i) THE INFORMATION AVAILABLE ON THE AGENTERO PLATFORM IS FREE OF ERRORS; (ii) THE FUNCTIONS OR SERVICES PROVIDED BY THE AGENTERO PLATFORM WILL BE UNINTERRUPTED, SECURE OR FREE OF ERRORS; (iii) DEFECTS WILL BE CORRECTED; OR (iv) THE AGENTERO PLATFORM OR THE SERVER(S) THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">WITHOUT LIMITING THE FOREGOING, none of AGENTERO OR AGENTERO’s affiliates, agents, directors, officers, employees, investors, suppliers OR licensors MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE AGENTERO PLATFORM, OR AS TO THE TIMELINESS, ACCURACY, RELIABILITY, COMPLETENESS OR CONTENT OF ANY SERVICEs, INFORMATION OR MATERIALS PROVIDED THROUGH OR IN CONNECTION WITH THE USE OF THE AGENTERO PLATFORM.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">No Consequential Damages. AGENTERO SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY DAMAGES FOR LOST DATA, BUSINESS INTERRUPTION, LOST PROFITS, LOST REVENUE OR LOST BUSINESS, ARISING OUT OF OR IN CONNECTION WITH THESE TERMS, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, INCLUDING WITHOUT LIMITATION, ANY SUCH DAMAGES ARISING OUT OF THE LICENSING, PROVISION OR USE OF THE AGENTERO PLATFORM, OR RESULTS THEREOF. AGENTERO WILL NOT BE LIABLE FOR THE COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Limits on Liability. AGENTERO’S AGGREGATE LIABILITY FOR ALL CLAIMS ARISING FROM THESE TERMS SHALL NOT EXCEED ONE U.S. DOLLAR ($1).</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Essential Purpose. You acknowledge that the terms in this Section 4 are an essential basis of the bargain described in these Terms and that, were Agentero to assume any further liability, any fees payable hereunder would out of necessity, be set much higher. THE LIMITATIONS IN THIS SECTION 4 SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW AND SHALL APPLY EVEN IF AN EXCLUSIVE OR LIMITED REMEDY STATED HEREIN FAILS OF ITS ESSENTIAL PURPOSE.</p>
                        <h2 className="privacy-section__title fs18 c-gray font-bold">5. TERMINATION.</h2>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Termination by Agentero. Agentero may terminate Your access to the Agentero Platform, in Agentero’s sole discretion, for any reason and at any time, with or without prior notice. It is Agentero’s policy to terminate Your access if You violate these Terms, as deemed appropriate in Agentero’s sole discretion, but Agentero may also terminate access as provided for in the preceding sentence. Agentero may terminate Your access to the Agentero Platform if You do not use Your Account for a lengthy period, as determined by Agentero from time to time in its sole discretion. You agree that Agentero is not liable to You or any third party for any termination of Your access to the Agentero Platform. You may not be entitled to create a new Account to access the Agentero Platform if Agentero has terminated Your prior Account. Agentero may also prohibit You from re-registering with the Agentero Platform, at Agentero’s sole discretion.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Termination by You. You may terminate Your Account at any time by following the instructions for terminating Your Account on the Agentero Platform. Please note that after deleting Your Account, Your Content will no longer be available; however, if any of Your Content was previously accessed by Agents, we are unable to delete such information from their systems.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Effects of Termination. After ten (10) days of the effective date of termination, Agentero shall have no obligation to maintain or provide any of Your Content and may thereafter unless legally prohibited, delete all Your Content in its systems or otherwise in its possession or under its control.</p>
                        <h2 className="privacy-section__title fs18 c-gray font-bold">6. AGREEMENT TO ARBITRATE.</h2>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Arbitration. You agree that all disputes between You and Agentero (whether or not such dispute involves a third party) arising out of or relating to these Terms, the Website, the Agentero Platform and/or Privacy Policy shall be finally resolved by arbitration before a single arbitrator conducted in the English language via teleconference or, if requested by You, in Berkeley, California, U.S.A., in each case under the Commercial Arbitration Rules of the American Arbitration Association (“AAA”) and You and Agentero hereby expressly waive trial by jury. You and Agentero shall appoint as sole arbitrator a person mutually agreed by You and Agentero or, if You and Agentero cannot agree within thirty (30) days of either party’s request for arbitration, such single arbitrator shall be selected by the AAA upon the request of either party. Each party shall equally bear the costs of the arbitration, except that, if You are an individual (not a corporate or similar entity), Agentero will bear the reasonable cost of the arbitrator and the AAA; in any event, each party will bear the cost of their own counsel. All decisions of the arbitrator shall be final and binding on both parties and enforceable in any court of competent jurisdiction. Notwithstanding this, application may be made to any court for a judicial acceptance of the award or order of enforcement. Notwithstanding the foregoing, either You or Agentero shall be entitled to seek injunctive relief, security or other equitable remedies from any court of competent jurisdiction. Under no circumstances shall the arbitrator be authorized to award damages, remedies or awards that conflict with these Terms (including without limitation Section 4 above) or to award punitive damages, including but not limited to pursuant to federal or state statutes permitting multiple or punitive awards. This Section 6 shall survive the expiration or termination of this Agreement.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Waiver of Class Actions. Any claims brought by You or Agentero must be brought in the party’s individual capacity, and not as a plaintiff or class member in any purported class or representative proceeding. Neither You nor Agentero will participate in a class action or class-wide arbitration for any claims covered by these Terms. You hereby waive any and all rights to bring any claims related to these Terms and Privacy Policy as a plaintiff or class member in any purported class or representative proceeding. You may bring claims only on Your own behalf.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Opt Out. You may opt out of this agreement to arbitrate in this Section 6. If You do so, neither You nor Agentero can require the other to participate in an arbitration proceeding. To opt out, You must notify Agentero in writing within thirty (30) days of the date that You first became subject to this arbitration provision. The opt out notice must state that You do not agree to the Agreement to Arbitrate and must include Your name, address, phone number, Your login credentials to which the opt out applies and a clear statement that You want to opt out of this agreement to arbitrate. You must sign the opt out notice for it to be effective. This procedure is the only way You can opt out of the Agreement to Arbitrate. You must use this address to opt out: Agentero, Inc., ATTN: Arbitration Opt-out, 2326 Rose Street, Berkeley, CA 94708.</p>
                        <h2 className="privacy-section__title fs18 c-gray font-bold">7. MISCELLANEOUS.</h2>
                        <p className="privacy-section__txt fs18 c-gray font-medium">General. You may not assign or transfer Your rights or obligations under these Terms in whole or in part to any third party without our written consent. These Terms shall bind and inure to the benefit of the parties to these Terms and their respective successors, permitted transferees and permitted assigns. We and You are independent contractors and are not partners, joint venturers, agents, employees or representatives of the other party. These Terms contain the entire understanding of the parties with respect to the transactions and matters contemplated herein, supersede all previous communications, understandings and agreements (whether oral or written) other than any click-through or end user license agreement provided by us, and cannot be amended except by a writing signed by both parties or by our posting of an amended version of these Terms on our Website. The headings and captions used in these Terms are used for convenience only and are not to be considered in construing or interpreting these Terms. If any part of these Terms is held to be unlawful, void or unenforceable, that part will be deemed severable and shall not affect the validity and enforceability of the remaining provisions. The failure of Agentero to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">Governing Law. These Terms and the rights and obligations of the parties to and under this agreement shall be governed by and construed under the laws of the State of California as applied to agreements entered into and to be performed in such State without giving effect to conflicts of laws rules or principles which would apply the laws of any other state or country. Subject in all respects to Section 6 hereof, for any disputes arising out of these Terms, the parties consent to exclusive jurisdiction and venue in the state and federal courts located in the State of California.</p>
                        <p className="privacy-section__txt fs18 c-gray font-medium">External Sites. The Agentero Platform may contain links to third-party web sites (“External Sites”). These links are provided solely as a convenience to You and not as an endorsement by us of the content on such External Sites. The content of such External Sites is developed and provided by others. You should contact the site administrator or webmaster for those External Sites if You have any concerns regarding such links or any content located on such External Sites. We are not responsible for the content of any linked External Sites and do not make any representations regarding the content or accuracy of any materials on such External Sites. You should take precautions when downloading files from all web sites to protect Your computer from viruses and other destructive programs. If You decide to access any External Sites, You do so at Your own risk.</p>
                    </div>
                </div>
            </section>
        );
    }
};

export default Terms;